


#ifdef USE_ROB2_IMAGES_FROM_0520
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00000.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_00, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00001.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_01, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00002.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_02, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00003.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_03, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00004.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_04, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00005.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_05, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00006.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_06, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00007.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_07, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00008.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_08, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00009.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_09, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00010.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_10, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00011.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_11, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00012.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_12, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00013.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_13, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00014.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_14, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00015.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_15, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00016.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_16, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00017.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_16, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00018.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_18, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00019.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_19, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00020.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_20, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00021.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_21, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00022.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_22, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00023.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_23, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00024.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_24, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00025.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_25, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00026.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_26, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00027.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_27, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00028.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_28, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00029.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_29, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00030.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_30, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00031.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_31, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00032.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_32, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00033.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_33, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onDark_20120520\\img00034.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_A_34, CAM_OCCUPANCY_GRID_X * data[i].gridY);





	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00000.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_00, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00001.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_01, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00002.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_02, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00003.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_03, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00004.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_04, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00005.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_05, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00006.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_06, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00007.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_07, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00008.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_08, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00009.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_09, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00010.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_10, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00011.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_11, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00012.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_12, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00013.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_13, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00014.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_14, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00015.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_15, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00016.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_16, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00017.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_16, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00018.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_18, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00019.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_19, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00020.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_20, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00021.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_21, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00022.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_22, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00023.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_23, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00024.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_24, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00025.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_24, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00026.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_26, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00027.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_27, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00028.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_28, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00029.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_29, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00030.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_30, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00031.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_31, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00032.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_32, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00033.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_33, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00034.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_34, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00035.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_35, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00036.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_35, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00037.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_37, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00038.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_38, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00039.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_39, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00040.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_35, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00041.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_41, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00042.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_42, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00043.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_43, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00044.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_44, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00045.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_35, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00046.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_46, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00047.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_47, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00048.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_48, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00049.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_49, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00050.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_50, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00051.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_35, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00052.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_52, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00053.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_53, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00054.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_54, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00055.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_55, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_darkerArea_onLight_20120520\\img00056.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_56, CAM_OCCUPANCY_GRID_X * data[i].gridY);







	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00000.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_00, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00001.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_01, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00002.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_02, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00003.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_03, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00004.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_04, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00005.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_05, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00006.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_06, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00007.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_07, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00008.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_08, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00009.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_09, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00010.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_10, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00011.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_11, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00012.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_12, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00013.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_13, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00014.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_13, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00015.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_15, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00016.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_16, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00017.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_17, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00018.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_18, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00019.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_18, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00020.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_20, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00021.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_21, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00022.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_22, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00023.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_23, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00024.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_24, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00025.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_24, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00026.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_26, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00027.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_27, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00028.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_27, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00029.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_29, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00030.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_30, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00031.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_30, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00032.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_32, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00033.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_33, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00034.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_34, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00035.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_35, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00036.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_36, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00037.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_36, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00038.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_35, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00039.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_35, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00040.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_40, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00041.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_41, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00042.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_42, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onDark_20120520\\img00043.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_C_43, CAM_OCCUPANCY_GRID_X * data[i].gridY);






	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00000.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_00, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00001.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_01, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00002.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_02, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00003.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_03, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00004.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_04, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00005.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_05, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00006.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_06, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00007.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_07, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00008.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_08, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00009.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_09, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00010.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_10, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00011.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_11, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00012.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_12, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00013.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_13, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00014.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_14, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00015.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_15, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00016.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_16, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00017.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_17, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00018.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_18, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00019.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_19, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00020.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_20, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00021.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_21, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00022.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_21, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00023.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_23, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00024.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_24, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00025.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_25, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00026.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_26, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00027.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_27, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00028.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_28, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00029.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_28, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00030.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_30, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00031.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_31, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00032.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_32, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00033.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_33, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00034.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_33, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00035.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_35, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00036.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_36, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00037.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_B_35, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00038.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_38, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00039.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_39, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00040.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_40, CAM_OCCUPANCY_GRID_X * data[i].gridY);
	++i;
	strcpy (data[i].imgName, "robot2_lighterArea_onLight_20120520\\img00041.dat"); data[i].orig = orig; data[i].flip = flip; data[i].gridY = CAM_OCCUPANCY_GRID_Y; data[i].isLoc = 0;
	memcpy (data[i].occupancyGrid, grid_r2_0520_D_41, CAM_OCCUPANCY_GRID_X * data[i].gridY);
#endif // USE_ROB2_IMAGES_FROM_0520


